# Introduction to Data Science 2025

# Week 1

## Exercise 1 | Matrix warm-up
<span style="background-color: #ccfff2"> *Note: You can find tutorials for NumPy and Pandas under 'Useful tutorials' in the course material.*</span>

One of the most useful properties of any scientific programming language (Python with NumPy, R, Julia, etc) is that they allow us to work with matrices efficiently. Let's learn more about these features!

### 1.1 Basics

1. Let's start by creating two arrays <span style="background-color: #ccfff2"> A</span> and <span style="background-color: #ccfff2"> B</span> which each have the integers <span style="background-color: #ccfff2"> 0, 1, 2, ..., 1e7-1</span>. Use the normal arrays or lists of the programming language you are using, e.g. *list* or *[ ]* or *numpy.array()* in Python.

In [1]:
import numpy as np

#create array with elements in the range from 0 to 1e7 - 1 (integers)
A = np.arange(int(1e7))
B = np.arange(int(1e7))

print('A = ', A)

A =  [      0       1       2 ... 9999997 9999998 9999999]


2. Create a function that uses a <span style="background-color: #ccfff2"> for loop</span> or equivalent to return a new array <span style="background-color: #ccfff2"> C</span>, which contains the <span style="background-color: #ccfff2"> element-wise sum of *A* and *B*</span>, e.g. C should contain the integers <span style="background-color: #ccfff2"> 0, 2, 4, etc</span>.

In [2]:
def add_with_for(A,B):
    C = np.zeros(len(A)) # initialize new array
    
    for i in range(len(A)):
        C[i] = A[i] + B[i] # element-wise sum
    return C

print('C = ', add_with_for(A, B))

C =  [0.0000000e+00 2.0000000e+00 4.0000000e+00 ... 1.9999994e+07 1.9999996e+07
 1.9999998e+07]


3. Next, let's create another function that uses NumPy (or equivalent) to do the same. To try it out, allocate two arrays (e.g. using <span style="background-color: #ccfff2"> np.array</span> in NumPy) and add the arrays together using your function. Don't use loops, instead, find out how to add the two arrays directly. What do you notice in comparison to the previous function?

In [3]:
C = np.add(A,B)
print('C = ', C) # Wow! So much faster!

C =  [       0        2        4 ... 19999994 19999996 19999998]


### 1.2 Array manipulation

<span style="background-color: #ccfff2"> *Note: for the following exercises, only use NumPy or equivalent functions. Don't use any loops.* </span>
1. Create the following array:

*[hint: <span style="background-color: #ccfff2"> np.reshape</span>]*

In [25]:
# array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
#        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
#        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
#        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
#        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
#        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
#        [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
#        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
#        [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
#        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [4]:
arr1 = np.arange(100) #Set elements in the range from 0 to 99

arr1 = arr1.reshape((10,10)) #Reshape the array to have dimensions (10,10)

print('arr = ')
print(arr1)

arr = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


2. Create the following array:

In [27]:
# array([[0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.],
#        [0., 1., 0., 1., 0., 1., 0., 1., 0., 1.]])

In [5]:
# Use this cell for your code
arr2 = np.array([0.,1.])

arr2 = np.tile(arr2, 50) #repeat pattern 50 times

arr2 = arr2.reshape((10,10)) #reshape to desired dimensions (10,10)

print('arr = ')
print(arr2)

arr = 
[[0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1. 0. 1. 0. 1.]]


3. Create the following array (D):

In [29]:
# array([[0., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.]])

In [6]:
D = np.ones((10,10)) # Create a (10,10) array consisting only of ones

np.fill_diagonal(D, 0) # Switch all the elements of the diagonal to zero

print('D = ')
print(D)

D = 
[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]]


4. Create the following array (E):

In [31]:
# array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
#        [1., 1., 1., 1., 1., 1., 1., 1., 0., 1.],
#        [1., 1., 1., 1., 1., 1., 1., 0., 1., 1.],
#        [1., 1., 1., 1., 1., 1., 0., 1., 1., 1.],
#        [1., 1., 1., 1., 1., 0., 1., 1., 1., 1.],
#        [1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
#        [1., 1., 1., 0., 1., 1., 1., 1., 1., 1.],
#        [1., 1., 0., 1., 1., 1., 1., 1., 1., 1.],
#        [1., 0., 1., 1., 1., 1., 1., 1., 1., 1.],
#        [0., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
E = np.rot90(D)

print('E = ')
print(E)

E = 
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 0. 1. 1.]
 [1. 1. 1. 1. 1. 1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1. 1. 1.]
 [1. 1. 0. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


5. Call the last two matrices <span style="background-color: #ccfff2">D</span> and <span style="background-color: #ccfff2">E</span>, respectively. Show that the determinant of their product (matrix multiplication) is the same as the product of their determinants. That is calculate both <span style="background-color: #ccfff2">det(DE)</span> and <span style="background-color: #ccfff2">det(D) * det(E)</span>, and show that they are the same. Is it a coincidence? (I think not) The product of the determinants (or the determinant of the product) should be -81.

In [8]:
D_det = np.linalg.det(D) # determinant of D

E_det = np.linalg.det(E) # determinant of E

print(D_det * E_det)

prod = np.dot(D, E) #product matrix

prod_det = np.linalg.det(prod) #determinant of product matrix

print(prod_det)

-81.0
-81.00000000000017


This is the distributive property of the determinant. It is an algebraic property such that the determinant of the product of two matrices is equal to the product of the determinant of each matrix separately.

### 1.3 Slicing

Array slicing is a powerful way to extract data from an array. Let's practice array slicing with the following exercises!

1. Load the [California housing dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_california_housing.html). The data should be a matrix of shape <span style="background-color: #ccfff2">(20640, 8)</span>, that is 20640 rows and 8 columns. Use the <span style="background-color: #ccfff2">.shape</span> attribute of NumPy arrays to verify this. Here's a [description of the fields](https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset).

In [9]:
from sklearn.datasets import fetch_california_housing

cali = fetch_california_housing()

print(cali.data.shape) # print dataset shape
print(cali['DESCR']) # print dataset description

(20640, 8)
.. _california_housing_dataset:

California Housing dataset
--------------------------

**Data Set Characteristics:**

:Number of Instances: 20640

:Number of Attributes: 8 numeric, predictive attributes and the target

:Attribute Information:
    - MedInc        median income in block group
    - HouseAge      median house age in block group
    - AveRooms      average number of rooms per household
    - AveBedrms     average number of bedrooms per household
    - Population    block group population
    - AveOccup      average number of household members
    - Latitude      block group latitude
    - Longitude     block group longitude

:Missing Attribute Values: None

This dataset was obtained from the StatLib repository.
https://www.dcc.fc.up.pt/~ltorgo/Regression/cal_housing.html

The target variable is the median house value for California districts,
expressed in hundreds of thousands of dollars ($100,000).

This dataset was derived from the 1990 U.S. census, using one

2. Select rows where the average number of bedrooms <span style="background-color: #ccfff2">(AveBedrms)</span> is higher than 2. The first few row indices should be <span style="background-color: #ccfff2">710,  1023,  1024, ...</span> (zero-indexed). Count these houses - how many rows are selected? *[hint: <span style="background-color: #ccfff2">np.where</span>]*

In [10]:
# Find row indices where average number of bedrooms > 2
houses = np.where(cali.data[:, 3] > 2)

houses_count = houses[0].shape[0] # Count rows

print('Houses with more bedrooms (row indices) = ', houses)
print('Number of houses (rows) with more bedrooms = ', houses_count)

Houses with more bedrooms (row indices) =  (array([  710,  1023,  1024,  1030,  1102,  1233,  1234,  1235,  1236,
        1238,  1239,  1240,  1566,  1867,  1871,  1872,  1879,  1881,
        1889,  1901,  1906,  1910,  1911,  1912,  1913,  1914,  1925,
        1926,  1978,  1979,  2392,  2395,  2396,  2397,  2398,  2510,
        2511,  2643,  2656,  2763,  2768,  2776,  2778,  3014,  3086,
        3095,  3258,  3292,  3293,  3313,  3314,  3334,  3349,  3350,
        9193,  9423,  9431,  9451,  9634,  9669,  9671,  9672,  9675,
        9676,  9678,  9679,  9680,  9681,  9682,  9683, 10067, 10076,
       10077, 10078, 10079, 10080, 10081, 10082, 10083, 10084, 10405,
       11705, 11706, 11707, 11708, 11709, 11710, 11711, 11713, 11714,
       11715, 11716, 11717, 11719, 11720, 11721, 11722, 11723, 11724,
       11725, 11729, 11831, 11832, 11833, 11834, 11847, 11848, 11849,
       11850, 11862, 11865, 11866, 11867, 11869, 11870, 12136, 12303,
       12305, 12306, 12307, 12324, 12325, 1234

3. Select the rows where the median house age (i.e. median in each block group) <span style="background-color: #ccfff2">(HouseAge)</span> is between 1 and 3 years (inclusive). There should be **124** of these.

In [11]:
house_age = np.where((cali.data[:, 1] >= 1)&(cali.data[:, 1] <= 3))

print('Houses selected within HouseAge interval (row indices) = ', house_age)
print('Number of houses (rows) within HouseAge interval = ', house_age[0].shape[0])

Houses selected within HouseAge interval (row indices) =  (array([   59,   854,   871,   959,   976,  1260,  1565,  1566,  1648,
        1719,  2206,  2310,  2311,  2312,  2336,  2339,  2706,  2774,
        2993,  3130,  3140,  5506,  9109,  9132,  9147,  9168,  9187,
        9378,  9639, 10336, 10376, 10391, 10401, 10403, 10406, 10410,
       10412, 10416, 10440, 10456, 10467, 10513, 10514, 10519, 10521,
       10524, 10525, 10529, 10548, 10619, 10622, 10631, 11490, 11775,
       12000, 12006, 12077, 12084, 12119, 12123, 12137, 12142, 12143,
       12151, 12156, 12167, 12171, 12201, 12202, 12203, 12204, 12285,
       12286, 12308, 12363, 12430, 12841, 12868, 13041, 13074, 13100,
       13102, 13139, 13177, 13179, 13367, 13368, 13373, 13374, 13375,
       13422, 13659, 13713, 13715, 13747, 13848, 13855, 14557, 15220,
       15444, 15464, 15736, 15785, 16383, 16566, 16593, 17068, 17824,
       17826, 17827, 18725, 18942, 18947, 18972, 18989, 19001, 19003,
       19033, 19046, 19536, 195

4. Find the mean of the block group population <span style="background-color: #ccfff2">(Population)</span> for homes whose median value is more than 25000 USD (the target variable). It should be around **1425.68**.

In [12]:
homes = np.where(cali.target > 0.25) # Houses with median value over $25,000

pop = cali.data[homes, 4] # From the selected rows, get the population column

mean_pop = np.mean(pop) # calculate mean of population

print("Mean block group population = ", mean_pop)

Mean block group population =  1425.6833737275813


## Exercise 2 | Working with text data

Next, let's look into some text data. We will be looking into Amazon reviews, and the necessary steps to transform a raw dataset into a format more suitable for prediction tasks.

1. Download the automotive 5-core dataset from [here](https://jmcauley.ucsd.edu/data/amazon_v2/categoryFilesSmall/Automotive_5.json.gz). Next, you can extract the data in <span style="background-color: #ccfff2">JSON</span> format. You can also download one of the bigger ones, if you are feeling ambitious. Open the JSON file. Access the <span style="background-color: #ccfff2">reviewText</span> field, which contains the unstructured review text written by the user.

For instance, the first review reads as follows: 

*'After I wrote the below review, the manufacturer contacted me and explained how to use this.  Instead of the (current) picture on Amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally. [...]'*

In [3]:
import pandas as pd
import string

data = pd.read_json("Automotive_5.json", lines=True)

print('A review example: ', data.iloc[1]['reviewText'])

A review example:  It sucks barely picks up anything definitely not for cars or pretty much anything don't waste your money


2. Next, let's follow some steps to normalize the text data.

When dealing with natural language, it is important to notice that while, for example, the words "Copper" and "copper" are represented by two different strings, they have the same meaning. When applying statistical methods on this data, it is useful to ensure that words with the same meaning are represented by the same string.

* <span style="background-color: #ccfff2">Downcasing</span>: Let's first downcase the contents of the <span style="background-color: #ccfff2">reviewText</span> field.

Now the first review should be:

*'after i wrote the below review, the manufacturer contacted me and explained how to use this.  instead of the (current) picture on amazon where the phone is placed vertically, you actually use the stand with the phone placed horizontally.'*

In [12]:
data['reviewText'] = data['reviewText'].str.lower()

print('Downcasing example: ', data.iloc[1]['reviewText'])

Downcasing example:  it sucks barely picks up anything definitely not for cars or pretty much anything dont waste your money


3. Let's continue with punctuation and stop word removal. Stop words are words like "and", "the", etc. They are usually very common words that have little to do with the actual content matter. There's plenty openly available lists of stop words for almost any (natural) language.

* <span style="background-color: #ccfff2">Punctuation and stop-word removal</span>: Let's now remove all punctuation, as well as the stop words. You can find a stop word list for English, e.g. [here](https://gist.github.com/xldrkp/4a3b1a33f10d37bedbe0068f2b4482e8#file-stopwords-en-txt).*(use the link to download a txt of english stopwords)* Save the stopwords in the file as "stopwords-en.txt".

First review at this point reads as: 

*'wrote review manufacturer contacted explained current picture amazon phone vertically stand phone horizontally'*

In [13]:
data['reviewText'] = data['reviewText'].str.replace(r'[^\w\s]+', '', regex=True)

print('Example after removing punctuation: ', data.iloc[1]['reviewText'])

Example after removing punctuation:  it sucks barely picks up anything definitely not for cars or pretty much anything dont waste your money


In [14]:
#remove stop words
with open("stopwords-en.txt") as f:
    stopwords = set(f.read().split("\n"))
    
data["reviewText"] = data['reviewText'].apply(lambda x: ' '.join([word for word in str(x).split() if word not in (stopwords)]))
print('Example after removing stopwords: ', data.iloc[1]['reviewText'])

FileNotFoundError: [Errno 2] No such file or directory: 'stopwords-en.txt'

4. Let's continue with stemming. For example, while the words "swims" and "swim" are different strings, they both refer to swimming. [Stemming](https://en.wikipedia.org/wiki/Stemming) refers to the process of mapping words from their inflected form to their base form, for instance: swims -> swim.

* <span style="background-color: #ccfff2">Stemming</span>: Apply a stemmer on the paragraphs, so that inflected forms are mapped to the base form. For example, for Python the popular natural language toolkit [nltk](http://www.nltk.org/howto/stem.html) has an easy to use stemmer. In case you are using R, you can try the [Snowball stemmer](https://www.rdocumentation.org/packages/corpus/versions/0.10.2/topics/stem_snowball). You can find out how to install nltk from [here](https://www.nltk.org/install.html). It will take a while to run! So, grab a coffee and wait :D

Finally, after stemming: 

*'wrote review manufactur contact explain current pictur amazon phone vertic stand phone horizont'*

In [ ]:
from nltk.stem.porter import *

ps = PorterStemmer() # Takes a while
data["reviewText"] = data["reviewText"].apply(lambda x: ' '.join([ps.stem(word) for word in str(x).split()]))

print('Review example after stemming: ', data.iloc[1]['reviewText'])

5. Finally, filter the data by selecting reviews where the field <span style="background-color: #ccfff2">overall</span> is 4 or 5, and store the review texts in a file named <span style="background-color: #ccfff2">pos.txt</span>. Similarly, select reviews with rating 1 or 2 and store them in a file named <span style="background-color: #ccfff2">neg.txt</span>. Ignore the reviews with overall rating 3. Each line in the two files should contain exactly one preprocessed review text without the rating.

In [10]:
pos = []
neg = []

for row in range(len(data)):
    if data.iloc[row]["overall"] > 3:
        pos.append(data.iloc[row]["reviewText"])
    elif data.iloc[row]["overall"] < 3:
        neg.append(data.iloc[row]["reviewText"])

with open("pos.txt", 'w') as f:
    f.write("\n".join(pos))

with open("neg.txt", 'w') as f:
    f.write("\n".join(neg))
    
# Check the generated files!

TypeError: sequence item 4505: expected str instance, float found

## Exercise 3 | SQL basics

Next, let's take a refresher on the basics of SQL. In this exercise, you will be working on the simplified Northwind 2000 SQLite database. You can download the database from Kaggle [here](https://courses.mooc.fi/api/v0/files/course/f92ffc32-2dd4-421d-87f3-c48800422cc5/files/VEKX2bxGCDGyojG902gmYZTXCnrAQw.zip).

To test your SQL queries and complete the exercise, you can download and install SQLite if you don't yet have it installed.

Please write SQL queries for the tasks on the simplified Northwind 2000 SQLite database.

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

2. Count how many orders each customer has placed.

3. Find the names of all customers who have ordered the product "Chai".

4. Find all orders that have been placed but not yet shipped.

5. Find the customer who has placed the most orders.

**Remember to submit your solutions. You can return this Jupyter notebook (.ipynb) or .py, .R, etc depending on your programming preferences. Remember to also submit your SQL queries. No need to submit the text files for the programming exercises.**

1. List the first name, last name, and hire date of all employees hired after January 1st, 1994.

```sql
SELECT
  FirstName,
  LastName,
  HireDate
FROM
  Employees
WHERE
  HireDate > '1994-01-01';
```

2. Count how many orders each customer has placed.

```sql
SELECT
  c.ContactName,
  COUNT(o.OrderID) AS number_of_orders
FROM
  Customers AS c
  JOIN Orders AS o ON c.CustomerID = o.CustomerID
GROUP BY
  c.CustomerID
ORDER BY
  number_of_orders DESC;
```

3. Find the names of all customers who have ordered the product "Chai".

```sql
SELECT DISTINCT
  c.ContactName
FROM
  Customers AS c
  JOIN Orders AS o ON c.CustomerID = o.CustomerID
  JOIN OrderDetails AS od ON o.OrderID = od.OrderID
  JOIN Products AS p ON od.ProductID = p.ProductID
WHERE
  p.ProductName = 'Chai';
```

4. Find all orders that have been placed but not yet shipped.

```sql
SELECT
  OrderID,
  CustomerID,
  OrderDate
FROM
  Orders
WHERE
  ShippedDate IS NULL;
```

5. Find the customer who has placed the most orders.

```sql
SELECT
  c.ContactName,
  COUNT(o.OrderID) AS order_count
FROM
  Customers AS c
  JOIN Orders AS o ON c.CustomerID = o.CustomerID
GROUP BY
  c.CustomerID
ORDER BY
  order_count DESC
LIMIT 1;
```